### ISSUE TITLE
hosted-engine deploy failed with VLAN_ID

### ISSUE THREAD

**Issue by vvetu** [oVirt/ovirt-ansible-hosted-engine-setup#285]
I'm trying to deploy the hosted-engine on a machine with vlan setup. From what i can tell the vlan id is correctly extracted but I can't figure it out what variable shouldn't be None and why is not set.
Any help appreciated

Host: CentOS 7.7.1908
oVirt: 4.3.8
`INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 TASK [ovirt.hosted_engine_setup : Detect VLAN ID]
INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 changed: [localhost]
DEBUG otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:103 TASK [ovirt.hosted_engine_setup : debug]
DEBUG otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:103 vlan_id_out: {'stderr_lines': [], u'changed': True, u'end': u'2020-01-29 11:37:31.444252', u'stdout': u'97', u'cmd': u"ip -d link show enp2s0f0.97 | grep 'vlan ' | grep -Po 'id \\K[\\d]+' | cat", 'failed': False, u'delta': u'0:00:00.007897', u'stderr': u'', u'rc': 0, 'stdout_lines': [u'97'], u'start': u'2020-01-29 11:37:31.436355'}
INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 TASK [ovirt.hosted_engine_setup : Set Engine public key as authorized key without validating the TLS/SSL certificates]
INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 changed: [localhost]
INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 TASK [ovirt.hosted_engine_setup : include_tasks]
INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 ok: [localhost]
INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 TASK [ovirt.hosted_engine_setup : Obtain SSO token using username/password credentials]
INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 ok: [localhost]
INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 TASK [ovirt.hosted_engine_setup : Ensure that the target datacenter is present]
INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 ok: [localhost]
INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 TASK [ovirt.hosted_engine_setup : Ensure that the target cluster is present in the target datacenter]
INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 ok: [localhost]
INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 TASK [ovirt.hosted_engine_setup : Check actual cluster location]
INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 skipping: [localhost]
INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 TASK [ovirt.hosted_engine_setup : Enable GlusterFS at cluster level]
INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 skipping: [localhost]
INFO otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:109 TASK [ovirt.hosted_engine_setup : Set VLAN ID at datacenter level]
DEBUG otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:103 {u'invocation': {u'module_args': {u'comment': None, u'external_provider': None, u'timeout': 180, u'description': None, u'name': u'ovirtmgmt', u'poll_interval': 3, u'state': u'present', u'nested_attributes': [], u'label': None, u'fetch_nested': False, u'vm_network': None, u'data_center': u'Default', u'clusters': None, u'vlan_tag': 97, u'mtu': None, u'id': None, u'wait': True}}, u'msg': u"Entity 'None' was not found.", u'exception': u'Traceback (most recent call last):\n  File "/tmp/ansible_ovirt_network_payload_3F32JI/ansible_ovirt_network_payload.zip/ansible/modules/cloud/ovirt/ovirt_network.py", line 327, in main\n  File "/tmp/ansible_ovirt_network_payload_3F32JI/ansible_ovirt_network_payload.zip/ansible/module_utils/ovirt.py", line 592, in create\n    new_entity = self.build_entity()\n  File "/tmp/ansible_ovirt_network_payload_3F32JI/ansible_ovirt_network_payload.zip/ansible/modules/cloud/ovirt/ovirt_network.py", line 175, in build_entity\n  File "/tmp/ansible_ovirt_network_payload_3F32JI/ansible_ovirt_network_payload.zip/ansible/module_utils/ovirt.py", line 327, in get_id_by_name\n    raise Exception("Entity \'%s\' was not found." % name)\nException: Entity \'None\' was not found.\n', u'changed': False, u'_ansible_no_log': False}
ERROR otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:107 Exception: Entity 'None' was not found.
ERROR otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:107 fatal: [localhost]: FAILED! => {"changed": false, "msg": "Entity 'None' was not found."}`

**Comment by vvetu** [comment]
For those how come across this...
The actual bug is in ovirt_network module
[Unable to create new logical network on oVirt ](https://github.com/ansible/ansible/issues/66858)
